language: java

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

before_script:
  - rm src/test/resources/settings.properties
  - echo "username="+$username > src/test/resources/settings.properties
  - echo "password="+$password >> src/test/resources/settings.properties
